### PR TITLE
Add ArborX

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by masterleinad** [comment]
https://github.com/spack/spack/pull/22486 allows `DataTransferKit` to use `ArborX` as an external package.

**Comment by masterleinad** [comment]
@balay ping Can we move forward here?

**Comment by balay** [comment]
Sorry about the late reply. 

Right now - we haven't yet started using this fork for xsdk@0.7.0 work. [so the branches here are stale]

Do I understand that arborx is now being added to xsdk collection? Or is it just a dependency to dtk?

cc: @ulrikeyang @balos1

**Comment by ulrikeyang** [comment]
Yes, ArborX will be part of the next release, so it would be great if we could include it in testing if possible.
Thanks

**Comment by masterleinad** [comment]
The part corresponding to the `xSDK Community Package Policies` is https://github.com/xsdk-project/xsdk-policy-compatibility/pull/34.

**Comment by balay** [comment]
right now xsdk@develop is broken. I'll have to look at getting that working - and then test this change.

Add move this MR to spack proper [from this fork - that is not currently used]

Also presumably we'll need to enable `datatransferkit+arborx` as part of xsdk@develop?

**Comment by masterleinad** [comment]
> Also presumably we'll need to enable `datatransferkit+arborx` as part of xsdk@develop?

Let me know which option is preferred. `Datatransferkit` will continue to support both modes.

**Comment by masterleinad** [comment]
> Add move this MR to spack proper [from this fork - that is not currently used]

See https://github.com/spack/spack/pull/22619.

**Comment by masterleinad** [comment]
Superseded by spack#22619.

**Pull request closed without merging**
